"""
scripts/generate_paper_metrics.py
===================================
Reads benchmark_report.json and ablation_results.json and generates:
  1. A LaTeX comparison table (ready to paste into the paper)
  2. A LaTeX ablation table
  3. A summary JSON with all key numbers the paper needs
  4. A confusion-matrix breakdown per system

Usage:
    python scripts/generate_paper_metrics.py
    python scripts/generate_paper_metrics.py --report outputs/benchmark_report.json

Output:
    outputs/paper_metrics.json    — all numbers in one place
    outputs/table_main.tex        — main comparison table
    outputs/table_ablation.tex    — ablation table (if ablation_results.json exists)
"""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

OUTPUTS_DIR = ROOT / "outputs"


def pct(v: float) -> str:
    """Format float as percentage string."""
    return f"{v * 100:.1f}"


def bold(s: str) -> str:
    """Wrap in LaTeX bold."""
    return f"\\textbf{{{s}}}"


def load_json(path: Path):
    if not path.exists():
        return None
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def find_best(metrics: dict, key: str) -> str:
    """Return the system name with highest value for the given key."""
    best_sys  = None
    best_val  = -1.0
    for sys_name, m in metrics.items():
        val = m.get(key, 0.0)
        if val > best_val:
            best_val = val
            best_sys = sys_name
    return best_sys


def generate_main_table(metrics: dict) -> str:
    """Generate LaTeX comparison table."""
    systems = list(metrics.keys())

    # Determine best values per column for bolding
    best_accuracy  = find_best(metrics, "accuracy")
    best_precision = find_best(metrics, "precision")
    best_recall    = find_best(metrics, "recall")
    best_f1        = find_best(metrics, "f1")

    display_names = {
        "insightswarm":  "InsightSwarm (Ours)",
        "single_agent":  "Single-Agent LLM",
        "keyword":       "Keyword Baseline",
    }

    rows = []
    for sys_name in systems:
        m    = metrics[sys_name]
        name = display_names.get(sys_name, sys_name)

        acc  = pct(m.get("accuracy",  0))
        prec = pct(m.get("precision", 0))
        rec  = pct(m.get("recall",    0))
        f1   = pct(m.get("f1",        0))

        if sys_name == best_accuracy:  acc  = bold(acc)
        if sys_name == best_precision: prec = bold(prec)
        if sys_name == best_recall:    rec  = bold(rec)
        if sys_name == best_f1:        f1   = bold(f1)

        rows.append(f"  {name:<30} & {acc} & {prec} & {rec} & {f1} \\\\")

    rows_str = "\n".join(rows)

    table = f"""% Auto-generated by scripts/generate_paper_metrics.py
\\begin{{table}}[h]
  \\centering
  \\caption{{Performance comparison on FEVER benchmark (binary SUPPORTS/REFUTES claims).
             Best results in bold.}}
  \\label{{tab:main_results}}
  \\begin{{tabular}}{{lrrrr}}
    \\toprule
    System & Acc.\\,(\\%) & Prec.\\,(\\%) & Recall\\,(\\%) & F1\\,(\\%) \\\\
    \\midrule
{rows_str}
    \\bottomrule
  \\end{{tabular}}
\\end{{table}}
"""
    return table


def generate_ablation_table(ablation: dict) -> str:
    """Generate LaTeX ablation table from ablation_results.json."""
    if not ablation or "results" not in ablation:
        return "% No ablation data available\n"

    configs = ablation["results"]

    rows = []
    best_f1 = max(c.get("f1", 0) for c in configs)
    full_f1 = next((c.get("f1", 0) for c in configs if c.get("config") == "full_system"), best_f1)

    for cfg in configs:
        name     = cfg.get("config_label", cfg.get("config", "Unknown"))
        acc      = pct(cfg.get("accuracy",  0))
        f1       = pct(cfg.get("f1",        0))
        delta    = cfg.get("f1", 0) - full_f1

        delta_str = f"{'−' if delta < 0 else '+'}{abs(delta*100):.1f}" if cfg.get("config") != "full_system" else "—"

        if cfg.get("f1", 0) == best_f1:
            f1 = bold(f1)

        rows.append(f"  {name:<40} & {acc} & {f1} & {delta_str} \\\\")

    rows_str = "\n".join(rows)

    return f"""% Auto-generated by scripts/generate_paper_metrics.py
\\begin{{table}}[h]
  \\centering
  \\caption{{Ablation study on FEVER (50-claim subset). $\\Delta$F1 is relative
             to the full system. Best F1 in bold.}}
  \\label{{tab:ablation}}
  \\begin{{tabular}}{{lrrr}}
    \\toprule
    Configuration & Acc.\\,(\\%) & F1\\,(\\%) & $\\Delta$F1 \\\\
    \\midrule
{rows_str}
    \\bottomrule
  \\end{{tabular}}
\\end{{table}}
"""


def generate_paper_metrics(report: dict, ablation: dict = None) -> dict:
    """Compile all numbers into a flat dict for easy paper writing."""
    metrics  = report.get("metrics", {})
    is_m     = metrics.get("insightswarm", {})
    sa_m     = metrics.get("single_agent", {})
    kw_m     = metrics.get("keyword", {})

    def delta(a, b, key):
        return round((a.get(key, 0) - b.get(key, 0)) * 100, 1)

    paper = {
        "insightswarm": {
            "accuracy":  round(is_m.get("accuracy",  0) * 100, 1),
            "precision": round(is_m.get("precision", 0) * 100, 1),
            "recall":    round(is_m.get("recall",    0) * 100, 1),
            "f1":        round(is_m.get("f1",        0) * 100, 1),
            "n_total":   is_m.get("n_total", 0),
            "n_binary":  is_m.get("n_binary", 0),
            "n_errors":  is_m.get("n_errors", 0),
            "avg_latency_s": is_m.get("avg_latency_s", 0),
            "mae_calibration": is_m.get("mae_calibration", 0),
        },
        "single_agent_baseline": {
            "accuracy":  round(sa_m.get("accuracy", 0) * 100, 1),
            "f1":        round(sa_m.get("f1",       0) * 100, 1),
        },
        "keyword_baseline": {
            "accuracy":  round(kw_m.get("accuracy", 0) * 100, 1),
            "f1":        round(kw_m.get("f1",       0) * 100, 1),
        },
        "improvements_over_single_agent": {
            "delta_accuracy_pct":  delta(is_m, sa_m, "accuracy"),
            "delta_f1_pct":        delta(is_m, sa_m, "f1"),
            "delta_precision_pct": delta(is_m, sa_m, "precision"),
            "delta_recall_pct":    delta(is_m, sa_m, "recall"),
        },
        "dataset": {
            "source":    report.get("dataset", ""),
            "n_claims":  report.get("n_claims", 0),
            "timestamp": report.get("timestamp", ""),
        },
    }

    if ablation and "results" in ablation:
        paper["ablation"] = ablation["results"]

    return paper


def main():
    parser = argparse.ArgumentParser(description="Generate paper metrics from benchmark results")
    parser.add_argument("--report",   type=str, default=None, help="Path to benchmark_report.json")
    parser.add_argument("--ablation", type=str, default=None, help="Path to ablation_results.json")
    args = parser.parse_args()

    report_path   = Path(args.report)   if args.report   else OUTPUTS_DIR / "benchmark_report.json"
    ablation_path = Path(args.ablation) if args.ablation else OUTPUTS_DIR / "ablation_results.json"

    report = load_json(report_path)
    if report is None:
        print(f"ERROR: benchmark_report.json not found at {report_path}")
        print("Run the benchmark first: python tests/benchmark_suite.py")
        sys.exit(1)

    ablation = load_json(ablation_path)
    if ablation is None:
        print("Note: ablation_results.json not found — skipping ablation table.")

    # Generate paper metrics summary
    paper_metrics = generate_paper_metrics(report, ablation)
    with open(OUTPUTS_DIR / "paper_metrics.json", "w") as f:
        json.dump(paper_metrics, f, indent=2)
    print(f"Saved: {OUTPUTS_DIR / 'paper_metrics.json'}")

    # Generate main comparison table
    metrics = report.get("metrics", {})
    if metrics:
        main_table = generate_main_table(metrics)
        with open(OUTPUTS_DIR / "table_main.tex", "w") as f:
            f.write(main_table)
        print(f"Saved: {OUTPUTS_DIR / 'table_main.tex'}")
        print("\nMain Table Preview:")
        print(main_table)

    # Generate ablation table
    if ablation:
        abl_table = generate_ablation_table(ablation)
        with open(OUTPUTS_DIR / "table_ablation.tex", "w") as f:
            f.write(abl_table)
        print(f"Saved: {OUTPUTS_DIR / 'table_ablation.tex'}")

    # Print key numbers for the paper
    is_m = paper_metrics.get("insightswarm", {})
    imp  = paper_metrics.get("improvements_over_single_agent", {})
    print("\n─── Key Numbers for Paper ─────────────────────────────")
    print(f"  InsightSwarm Accuracy:  {is_m.get('accuracy')}%")
    print(f"  InsightSwarm F1:        {is_m.get('f1')}%")
    print(f"  Avg Latency:            {is_m.get('avg_latency_s')}s")
    print(f"  ΔF1 vs single-agent:   {imp.get('delta_f1_pct')}%")
    print(f"  ΔAcc vs single-agent:  {imp.get('delta_accuracy_pct')}%")
    print("────────────────────────────────────────────────────────")


if __name__ == "__main__":
    main()
